export const WORKOUT_ACTION_TYPES = {
  SET_WORKOUT: "SET_WORKOUT",
  REMOVE_WORKOUT: "REMOVE_WORKOUT",
  SET_EDIT_VALUES_AND_TOGGLE_WORKOUT_MODAL:
    "SET_EDIT_VALUES_AND_TOGGLE_WORKOUT_MODAL",
  EDIT_WORKOUT: "EDIT_WORKOUT",
  ARR_TO_LOAD: "ARR_TO_LOAD",
};
